baseurl = "http://kalug.linux.org.tw"
DefaultContentLanguage = "en"
title = "Kaohsiung Linux User Group"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
DisqusShortname = "kalug-linux-org-tw"
hasCJKLanguage = true

[blackfriday]
	# 讓 meetup 裡的 markdown 內容可以自動換行 
	extensions = ["hardLineBreak"] 

[Params]
  #subtitle = "高雄Linux使用者協會 我們每月定期第四個週六下午聚會"
  logo = "img/kalug.png"
  favicon = "img/kalug.ico"

  # hugo 的標準時間是 2006-01-02
  dateFormat = "January 2, 2006"
  
  commit = true
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true

[Author]
  website = "http://kalug.linux.org.tw"
  # email = "youremail@domain.com"
  facebook = "groups/kalug.tw"
  github = "kalug"
  telegram = "joinchat/Bqbim0F9EuW-GMUbYg9geA"

[[menu.main]]
    name = "Meetups"
    url = "meetups/"
    weight = 1

[[menu.main]]
    name = "Planet"
    url = "planet/"
    weight = 1

[[menu.planet]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    identifier = "pages"
    name = "Pages"
    weight = 2

[[menu.main]]
    parent = "pages"
    name = "Special Interest Group"
    url = "pages/sig"
    weight = 1

[[menu.main]]
    parent = "pages"
    name = "Useful Devices"
    url = "pages/UsefulDevices"
    weight = 2

[[menu.main]]
    parent = "pages"
    name = "Kaohsiung Life"
    url = "pages/Kaohsiung"
    weight = 3

[[menu.main]]
    identifier = "about"
    name = "About"
    weight = 3

[[menu.main]]
    parent = "about"
    name = "us"
    url = "about/us"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "Sponsors"
    url = "about/sponsors"
    weight = 2
